default: &default
  adapter: postgresql
  encoding: unicode
  database: shadows_of_brimstone_<%= Rails.env %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  <% unless ENV['DATABASE_USER'].blank? %>
  username: <%= ENV['DATABASE_USER'] %>
  <% end %>
  <% unless ENV['DATABASE_PASSWORD'].blank? %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  <% end %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default

production:
  url: <%= ENV['DATABASE_URL'] %>
