# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e33604ed5326192054e3f203a035a482d21acf57de66c2053e383af56293fd42510acf41e624f0f36515b0c8b6ae8ece9ea9b4f1654bf47f1b2413d3a4a96bd2

test:
  secret_key_base: 8f80218695b54b4ade0ea5f375236d2246b626ddfb22402a793d0de7033e36089e61e52fef83ffaf7c607b8aaef9ea826bef300d2501518cd2a465a54246699c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
